### ISSUE TITLE
First Crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#1]
If it's not a problem, I'll open an issue in your mod, so the message doesn't get lost in the other topic https://github.com/azerothcore/azerothcore-wotlk/issues/2159

After turning on the server normally:
![WoWScrnShot_032322_091939](https://user-images.githubusercontent.com/58153179/159718476-db153240-d1c6-42db-8b25-55f983fd1b16.jpg)

It crashed after a few minutes:
![image](https://user-images.githubusercontent.com/58153179/159715974-64839720-a6dd-4808-9a09-e2a7e053b04b.png)
![image](https://user-images.githubusercontent.com/58153179/159716113-b729c8d8-a0d4-4813-87e3-929be5a903f9.png)
![image](https://user-images.githubusercontent.com/58153179/159716078-79e54aef-6600-4cce-8ad8-58ff3f3eec86.png)

**Comment by ZhengPeiRu21** [comment]
Thank you for the report! This is a very interesting crash. I will look into it.

**Comment by ZhengPeiRu21** [comment]
Hopeful resolved in https://github.com/ZhengPeiRu21/mod-playerbots/commit/180014eb88200045a7a7068f3f5cbe729bb54df5.

**Comment by cthu1hoo** [comment]
sorry for offtopic, but thank you for coming forward to develop this further. 👍
