### ISSUE TITLE
seventh fall

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#10]
![Screenshot_2022-03-25-15-57-42-741_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160184955-eab08496-d160-4fad-a95f-9cb5ca61d794.jpg)
![Screenshot_2022-03-25-15-58-24-098_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160184964-f9fe41d7-db3c-4638-a175-e4d9cbdf4afc.jpg)
![Screenshot_2022-03-25-15-58-30-882_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160184965-186ff7af-a13e-4caf-a1ba-439416747751.jpg)
![Screenshot_2022-03-25-15-58-40-188_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160184968-21ff16b8-b2cb-4cdb-991e-818820142c70.jpg)
![Screenshot_2022-03-25-15-58-50-151_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160184970-0da60b1c-9c28-4592-88e1-0f0890dab3ef.jpg)
![Screenshot_2022-03-25-15-59-07-644_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160184974-b33ccf65-d32b-4451-9ffa-92d7c4e2a107.jpg)
![Screenshot_2022-03-25-15-59-17-465_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160184975-6eca5885-f71d-4865-b12c-cf42d86fd733.jpg)
![Screenshot_2022-03-25-15-59-29-990_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160184979-9cc0ae19-3dc2-469a-a97a-1e6139b30fcb.jpg)

**Comment by ZhengPeiRu21** [comment]
Thank you for the report. Hopefully is resolve with https://github.com/ZhengPeiRu21/mod-playerbots/commit/246b5b021dc3f4342c34ab4af850e0318294c4b8.
