### ISSUE TITLE
fatal error: use of overloaded operator '!=' is ambiguous (with operand types 'WorldPosition' and 'WorldPosition')

### ISSUE THREAD

**Issue by hallinbirch** [ZhengPeiRu21/mod-playerbots#101]
i keep trying to build and keep getting this error Docker or Native on Arch rolling 
/azerothcore/modules/mod-playerbots/src/strategy/actions/MovementActions.cpp:304:40: fatal error: use of overloaded operator '!=' is ambiguous (with operand types 'WorldPosition' and 'WorldPosition')
                if (telePos && telePos != movePosition)
this is after i tell it to install libboost-thread-dev to kinda fix the first error .... you know that one the win 10 person is having problems with
and idk f it had aynthing to do with it but i had to turn off PCH becuse the PCH file doesn't seem to in my new copy of the AC-WOTLK player bot branch right now
but yeah i can't seem to figure out how to fix the ambiguous != thing

**Comment by ZhengPeiRu21** [comment]
Thank you for the report. It seems you do not have the most up to date version of the module. This error should have already been resolved. Please re-open the issue if you continue to see problem with the most up to date code.
