### ISSUE TITLE
Segment fault

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#102]
Crash LOG:
[gdb.txt](https://github.com/ZhengPeiRu21/mod-playerbots/files/9635488/gdb.txt)

**Comment by ZhengPeiRu21** [comment]
Thank you for the report, fixed in https://github.com/ZhengPeiRu21/mod-playerbots/commit/5600e94e559c11c909dfd486452795afc68ee3e6
