### ISSUE TITLE
Bots crash instanced zones

### ISSUE THREAD

**Issue by thepopdog** [ZhengPeiRu21/mod-playerbots#104]
I entered the Deadmines with a team of bots. 2-3 minutes later the entire server crashes with a segmentation fault. There was no error output otherwise and nothing showed in the logs. I did this multiple times with the same result.

**Comment by ZhengPeiRu21** [comment]
Thank you for the reporting. If you are able to share a crash dump from the server's Crashes folder, that would be helpful.

**Comment by thepopdog** [comment]
I cannot find a Crashes directory or any dump files. Do I need to recompile as debug for that output?

**Comment by htc16** [comment]
> I cannot find a Crashes directory or any dump files. Do I need to recompile as debug for that output?

Please follow this tutorial to learn how to use the AC debugger.

Link: https://www.azerothcore.org/wiki/how-to-restart-and-debug

**Comment by thepopdog** [comment]
Found some time to recompile, etc. Here's the dump, or the closest thing to one.

[gdb.txt](https://github.com/ZhengPeiRu21/mod-playerbots/files/9688218/gdb.txt)

**Comment by ZhengPeiRu21** [comment]
Thank you for the debug log! That makes it very easy to fix. Crash is fixed in https://github.com/ZhengPeiRu21/mod-playerbots/commit/5cfac7bf71589317abc75c8d61b5eed46ceb1127.

**Comment by thepopdog** [comment]
Glad I could help!
