### ISSUE TITLE
Segment fault

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#105]
Hello Zheng!

I believe this log is related to the Battlegrounds crash.

Full log below.

[gdb.txt](https://github.com/ZhengPeiRu21/mod-playerbots/files/9642029/gdb.txt)

**Comment by ZhengPeiRu21** [comment]
This should be resolved in https://github.com/ZhengPeiRu21/mod-playerbots/commit/0a62ee004121356fa8bcc7473183c31404d626b6.
