### ISSUE TITLE
eighth fall

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#11]
![Screenshot_2022-03-25-16-42-16-346_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160190521-c4845831-fe25-41b9-898e-a22799ff062f.jpg)
![Screenshot_2022-03-25-16-42-28-509_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160190526-9aa4affb-289a-4cc7-bb13-3bfa0bd18617.jpg)

**Comment by ZhengPeiRu21** [comment]
Thank you for report this error. This looks like it is caused by an earlier fix. Could you please check with this latest commit and see if crash is improved? https://github.com/ZhengPeiRu21/mod-playerbots/commit/9797dd03717ec808b9451e988a7a56f4d9338663
