### ISSUE TITLE
New Segmentation fault

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#116]
After this PR https://github.com/ZhengPeiRu21/mod-playerbots/pull/115, I debugged the following log.

[gdb.txt](https://github.com/ZhengPeiRu21/mod-playerbots/files/9729605/gdb.txt)

**Comment by ZhengPeiRu21** [comment]
This was caused by having a ReturnDelay lower than 2000, so the urand call will error. Fixed in https://github.com/ZhengPeiRu21/mod-playerbots/commit/5d0aa407d6393051779e6c558ebbdbc822dc2f37.
