### ISSUE TITLE
octave fail

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#12]
![image](https://user-images.githubusercontent.com/58153179/160206634-c0347c92-3841-417e-8045-b3c81be8a07b.png)
![image](https://user-images.githubusercontent.com/58153179/160206809-5fd7f180-5dee-459c-a605-b42f5e25b39a.png)
![image](https://user-images.githubusercontent.com/58153179/160206917-daf356c1-c743-4bff-9381-4163dc735023.png)

**Comment by ZhengPeiRu21** [comment]
Resolved with https://github.com/ZhengPeiRu21/mod-playerbots/commit/41bcfbfcb6aa783c9ad91c4ce64bc8c21ef148f2
