### ISSUE TITLE
Bot talents not working not sure if this would be a solution

### ISSUE THREAD

**Issue by corker22** [ZhengPeiRu21/mod-playerbots#120]
so i can tell they think they have the talents but they do not. i was wondering would it be possible to allow the player to open the bots talents and manually select the bots talents as a workaround? enabling this may help work on bots using lfg and bgs. the lack of talents may be linked to them not using lfg

**Comment by ZhengPeiRu21** [comment]
Thank you for the idea! Unfortunately this would not be possible without client modifications. The client's talent UI is only for the player's talents. I think it will be easier to fix the original issue and let the bots choose appropriate talents.

**Comment by drozco** [comment]
There used to be an addon called Talented that may be possible to modify that to communicate with the playerbots somehow?  Or somehow allow the talents to be imported/exported using a string to encode the talent trees like the talent calculators do?
