### ISSUE TITLE
[question] server installation

### ISSUE THREAD

**Issue by xBarselonx** [ZhengPeiRu21/mod-playerbots#130]
hi all!
Previously, in the folder (https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbot/modules) there was already a module (https://github.com/ZhengPeiRu21/mod-playerbots). Now this mod is not in this folder. How to install a server with Playerbot now?

**Comment by virgo77** [comment]
Hi, you could search a bit for it by just clicking on the [main page](https://github.com/ZhengPeiRu21)!

Just git, in the 'modules' folder, before compiling

**Comment by ZhengPeiRu21** [comment]
Git does not support a submodule always linking to head, so the previous submodule was always out of date. The module should just be cloned directly from the repo: https://github.com/ZhengPeiRu21/mod-playerbots
