### ISSUE TITLE
mod-playerbots module installation issue

### ISSUE THREAD

**Issue by alfieo** [ZhengPeiRu21/mod-playerbots#131]
[ 13%] Building CXX object modules/CMakeFiles/modules.dir/mod-playerbots/src/ChatFilter.cpp.o
/home/tricore/acore/modules/mod-playerbots/src/ChatFilter.cpp:166:47: error: no member named 'GetTargetIcon' in 'Group'
                ObjectGuid rtiTarget = group->GetTargetIcon(RtiTargetValue::GetRtiIndex(rti.substr(1)));
                                       ~  ^
1 error generated.
make[2]:  [modules/CMakeFiles/modules.dir/build.make:104: modules/CMakeFiles/modules.dir/mod-playerbots/src/ChatFilter.cpp.o] Error 1
make[1]:  [CMakeFiles/Makefile2:1100: modules/CMakeFiles/modules.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by virgo77** [comment]
he he he, I think it's like me, when I tried to use it for the first time!

Question: did you download the 'playerbot' branch of AzerothCore? If not, pull the correct branch, then compile again. You will have a lot of warnings, but no errors. And the core will run correctly.

Check this [post](https://github.com/ZhengPeiRu21/mod-playerbots/issues/118#issuecomment-1273737472) (mine) :)

**Comment by alfieo** [comment]
Nah, your issue is different. They are all warnings not errors. Mine is definitely an error.

**Comment by ZhengPeiRu21** [comment]
Virgo77 is actually correct. This issue means you are not building using the right source. You need to be using the correct fork and the correct branch. Are you using the Playerbot branch of the AzerothCore fork link in the README?

**Comment by alfieo** [comment]
I can't use your fork because I need to use the PR for openSSL 3.0 on the main fork to compile. Otherwise I will not be able to compile even the main source without modules

**Comment by ZhengPeiRu21** [comment]
In that case, you will need to wait until the OpenSSL PR is merged with master so that it will be integrated with the fork to use the Playerbots module. There is no way to use it without the custom fork.

**Comment by alfieo** [comment]
Is it possible for you to have that on your fork too so I can grab it from your github and then compile?

**Comment by alfieo** [comment]
Or maybe guide me how to apply that feat/openssl PR to your fork?

**Comment by virgo77** [comment]
so you should be more precise about your issue.
Actually, the official AzerothCore is not currently supporting OpenSSL3.
It is said here, on the 2 first lines: https://www.azerothcore.org/wiki/installation

```
IMPORTANT NOTE
OpenSSL 3.x is NOT SUPPORTED. Use the version the installation guide points to.

Ubuntu 22.0 and later ships with OpenSSL 3.x! If you want to use Ubuntu, use a lower version or compile a lower version of OpenSSL
...
```
