### ISSUE TITLE
2 errors at compilation

### ISSUE THREAD

**Issue by bogdahn-fr** [ZhengPeiRu21/mod-playerbots#133]
during compilation (acore from ZhengPeiRu21, and playerbots module) two errors occur : 
`azerothcore-wotlk/modules/mod-playerbots/src/ChatFilter.cpp:166:47: fatal error: no member named 'GetTargetIcon' in 'Group'
                ObjectGuid rtiTarget = group->GetTargetIcon(RtiTargetValue::GetRtiIndex(rti.substr(1)));12: 
                                       ~~~~~  ^
`

and 

`azerothcore-wotlk/modules/mod-playerbots/src/strategy/actions/EmoteAction.h:17:6: fatal error: enumeration previously declared with nonfixed underlying type
enum TextEmotes : uint32;
`
Tested on linux mint and arch.

**Comment by ZhengPeiRu21** [comment]
It seems you are not using the correct AzerothCore codebase. Please make sure you are using the Playerbot branch of the fork linked in the README.

**Comment by bogdahn-fr** [comment]
> It seems you are not using the correct AzerothCore codebase. Please make sure you are using the Playerbot branch of the fork linked in the README.

i used your repo for acore, as mentionned

**Comment by bogdahn-fr** [comment]
i retry again, with the repo in the readme (as i did), same errors.

**Comment by ZhengPeiRu21** [comment]
Are you using the Playerbot branch of that repo, not master branch?

**Comment by bogdahn-fr** [comment]
You was right, i'm not use to use branchs, and since it was on the url, i assumed this was the correct branch :/ sorry for the trouble.
