### ISSUE TITLE
New Segment Fault

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#134]
Hello Zheng!

After 2 days online, a random crash.

[gdb.txt](https://github.com/ZhengPeiRu21/mod-playerbots/files/9966294/gdb.txt)

**Comment by ZhengPeiRu21** [comment]
Thank you for the report! I will take a look!

**Comment by ZhengPeiRu21** [comment]
This should be resolved in https://github.com/ZhengPeiRu21/mod-playerbots/commit/42bbe9dcdcac666a74185cfbb9e0f7e710905d01.
