### ISSUE TITLE
playerbot已经没救了，没有前途

### ISSUE THREAD

**Issue by zbhcn** [ZhengPeiRu21/mod-playerbots#137]
因为太弱智了，太多BUG，太多带崩服务端的错误，就连编译都无法顺利完成，而且长年不更新，不修复。

**Comment by ZhengPeiRu21** [comment]
不好意思，我只是空闲的时候才有时间稍微开发一点，所以不是特别快。如果你想让进度快一点，你可以提交一个PR。

如果你只是要跟机器人玩，我建议你看一眼这个。它已经做好了，所以没有bug，虽然它不如playerbots那么多功能。
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

**Comment by Haoren-Ruby** [comment]
作者大佬别理他，他这典型的放下碗骂娘！

**Comment by rogerc66** [comment]
> 因为太弱智了，太多BUG，太多带崩服务端的错误，就连编译都无法顺利完成，而且长年不更新，不修复。

如果不能做贡献就不要唧唧歪歪

**Comment by garfieldz90** [comment]
你以为人家是收钱写给你的么，说这种话。
