### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by rogerc66** [ZhengPeiRu21/mod-playerbots#14]
Compile error observed at 73% of process.

<img width="1125" alt="Screen Shot 2022-03-25 at 10 42 36 PM" src="https://user-images.githubusercontent.com/4217584/160227895-b3995812-d7b5-4442-a8cc-4a58fd471c1e.png">

**Comment by rogerc66** [comment]
I have used hack way to make it compiled first, but I'm sure it's not supposed to be a perfect solution.

`if (telePos && telePos != movePosition)`   to  `if (telePos && not (telePos == movePostion))`

**Comment by ZhengPeiRu21** [comment]
Thank you for report this. I'm glad you've found a temporarily solution that is working for you. Could you please share some details of your build environment? (OS version, g++ version, boost version, etc.) I will try to resolve this error so others are not having same trouble.

**Comment by rogerc66** [comment]
I'm on Ubuntu 20.04, Clang version 10.0.0, cmake version 3.16, boost version 1.71
Ubuntu is a VM running on a Synology NAS.

**Comment by htc16** [comment]
I think you need cmake 3.18 and clang 11

**Comment by rogerc66** [comment]
> I think you need cmake 3.18 and clang 11

ok, I will try them

**Comment by wraix** [comment]
I get this error to. I am not sure it is a good idea ever to use comparison like == or != on vectorial objects that contains floats as floats will almost always be different on the last decimals due to the rounding errors of how they work in hardware. A better comparisson would be to say "vector A" and vector B are equal iff they differ by some small epsillon. I am pretty sure that that functionality is already implemented somewhere in the azerothcore.

**Comment by ZhengPeiRu21** [comment]
> I get this error to. I am not sure it is a good idea ever to use comparison like == or != on vectorial objects that contains floats as floats will almost always be different on the last decimals due to the rounding errors of how they work in hardware. A better comparisson would be to say "vector A" and vector B are equal iff they differ by some small epsillon. I am pretty sure that that functionality is already implemented somewhere in the azerothcore.

Thank you for the helpful suggestion. I will find time to fix this comparison.

**Comment by ZhengPeiRu21** [comment]
I have changed this line to more secure in https://github.com/ZhengPeiRu21/mod-playerbots/commit/90be77baaed5af28b2d61d0f84032f308ac89c33. Please let me know if this resolve the issue for you.

**Comment by youhuowa** [comment]
azerothcore-wotlk/modules/mod-playerbots/src/strategy/actions/MovementActions.cpp:455:82: fatal error: use of overloaded operator '!=' is ambiguous (with operand types 'WorldPosition' and 'WorldPosition')
    if (sPlayerbotAIConfig->hasLog("bot_movement.csv") && lastMove.lastMoveShort != movePosition)

There is another line in MovementActions.cpp

**Comment by rogerc66** [comment]
> azerothcore-wotlk/modules/mod-playerbots/src/strategy/actions/MovementActions.cpp:455:82: fatal error: use of overloaded operator '!=' is ambiguous (with operand types 'WorldPosition' and 'WorldPosition') if (sPlayerbotAIConfig->hasLog("bot_movement.csv") && lastMove.lastMoveShort != movePosition)
> 
> There is another line in MovementActions.cpp

Confirmed,  changed to the same line above and it compiled.

**Comment by ZhengPeiRu21** [comment]
Thank you again for finding these comparisons. I have fixed this other one in https://github.com/ZhengPeiRu21/mod-playerbots/commit/7e2a87a7ea96f00cbd8c3cd2524b57b371799482.

**Comment by rogerc66** [comment]
> Thank you again for finding these comparisons. I have fixed this other one in [7e2a87a](https://github.com/ZhengPeiRu21/mod-playerbots/commit/7e2a87a7ea96f00cbd8c3cd2524b57b371799482).

Thank you for your good working, I think this issue can be closed.
