### ISSUE TITLE
Worldserver can't boot after installing module

### ISSUE THREAD

**Issue by CaspertheMighty** [ZhengPeiRu21/mod-playerbots#141]
Hello,

I am using the dockerized method to run the server, based on the playerbots branch. I got it to boot prior to configuring the module, but am now running up against a wall when starting the app:

azerothcore-wotlk-ac-worldserver-1  | Running without GDB
azerothcore-wotlk-ac-worldserver-1  | AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)
azerothcore-wotlk-ac-worldserver-1  | <Ctrl-C> to stop.
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  |    █████╗ ███████╗███████╗██████╗  ██████╗ ████████╗██╗  ██╗
azerothcore-wotlk-ac-worldserver-1  |   ██╔══██╗╚══███╔╝██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║  ██║
azerothcore-wotlk-ac-worldserver-1  |   ███████║  ███╔╝ █████╗  ██████╔╝██║   ██║   ██║   ███████║
azerothcore-wotlk-ac-worldserver-1  |   ██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗██║   ██║   ██║   ██╔══██║
azerothcore-wotlk-ac-worldserver-1  |   ██║  ██║███████╗███████╗██║  ██║╚██████╔╝   ██║   ██║  ██║
azerothcore-wotlk-ac-worldserver-1  |   ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
azerothcore-wotlk-ac-worldserver-1  |                                  ██████╗ ██████╗ ██████╗ ███████╗
azerothcore-wotlk-ac-worldserver-1  |                                 ██╔════╝██╔═══██╗██╔══██╗██╔════╝
azerothcore-wotlk-ac-worldserver-1  |                                 ██║     ██║   ██║██████╔╝█████╗
azerothcore-wotlk-ac-worldserver-1  |                                 ██║     ██║   ██║██╔══██╗██╔══╝
azerothcore-wotlk-ac-worldserver-1  |                                 ╚██████╗╚██████╔╝██║  ██║███████╗
azerothcore-wotlk-ac-worldserver-1  |                                  ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  |      AzerothCore 3.3.5a  -  www.azerothcore.org
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | > Using configuration file       /azerothcore/env/dist/etc/worldserver.conf
azerothcore-wotlk-ac-worldserver-1  | > Using SSL version:             OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
azerothcore-wotlk-ac-worldserver-1  | > Using Boost version:           1.71.0
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Process priority class set to -15
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Loading Modules Configuration...
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Using modules configuration:
azerothcore-wotlk-ac-worldserver-1  | > playerbots.conf.dist
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Initializing Scripts...
azerothcore-wotlk-ac-worldserver-1  | > Loading C++ scripts
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Opening DatabasePool 'acore_auth'. Asynchronous connections: 1, synchronous connections: 1.
azerothcore-wotlk-ac-worldserver-1  | DatabasePool 'acore_auth' opened successfully. 2 total connections running.
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Opening DatabasePool 'acore_characters'. Asynchronous connections: 1, synchronous connections: 2.
azerothcore-wotlk-ac-worldserver-1  | DatabasePool 'acore_characters' opened successfully. 3 total connections running.
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Opening DatabasePool 'acore_world'. Asynchronous connections: 1, synchronous connections: 1.
azerothcore-wotlk-ac-worldserver-1  | DatabasePool 'acore_world' opened successfully. 2 total connections running.
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Updating Auth database...
azerothcore-wotlk-ac-worldserver-1  | >> Auth database is up-to-date! Containing 1 new and 31 archived updates.
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Updating Character database...
azerothcore-wotlk-ac-worldserver-1  | >> Character database is up-to-date! Containing 3 new and 54 archived updates.
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Updating World database...
azerothcore-wotlk-ac-worldserver-1  | >> World database is up-to-date! Containing 321 new and 3160 archived updates.
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Opening DatabasePool 'acore_playerbots'. Asynchronous connections: 1, synchronous connections: 1.
azerothcore-wotlk-ac-worldserver-1  | Could not connect to MySQL database at 127.0.0.1: Can't connect to MySQL server on '127.0.0.1:3306' (111)
azerothcore-wotlk-ac-worldserver-1  | DatabasePool Playerbots NOT opened. There were errors opening the MySQL connections. Check your log file for specific errors
azerothcore-wotlk-ac-worldserver-1  | exit code: 1
azerothcore-wotlk-ac-worldserver-1  | worldserver terminated, restarting...
azerothcore-wotlk-ac-worldserver-1  | worldserver Terminated after 1 seconds, termination count: : 6
azerothcore-wotlk-ac-worldserver-1  | worldserver Restarter exited. Infinite crash loop prevented. Please check your system

I pulled the module through git, created the acore user with the password specified in the config file, and then ran the create_mysql.sql script. Afterwards I loaded all the scripts in the base folder and those in the characters and world directory. I can successfully connect as the acore user through HeidISQL, even as the commandline keeps repeating this error. Did I miss something?

**Comment by CaspertheMighty** [comment]
I have reinstalled everything and the error changed:

azerothcore-wotlk-ac-worldserver-1  | Opening DatabasePool 'acore_playerbots'. Asynchronous connections: 1, synchronous connections: 1.
azerothcore-wotlk-ac-worldserver-1  | DatabasePool 'acore_playerbots' opened successfully. 2 total connections running.
azerothcore-wotlk-ac-worldserver-1  |
azerothcore-wotlk-ac-worldserver-1  | Updating Playerbots database...
azerothcore-wotlk-ac-worldserver-1  | DBUpdater: The given source directory /azerothcore/modules/mod-playerbots does not exist, change the path to the directory where your sql directory exists (for example c:\source\trinitycore). Shutting down.
azerothcore-wotlk-ac-worldserver-1  | Could not update the Playerbots database, see log for details.
azerothcore-wotlk-ac-worldserver-1  | Closing down DatabasePool 'acore_playerbots'.
azerothcore-wotlk-ac-worldserver-1  | Asynchronous connections on DatabasePool 'acore_playerbots' terminated. Proceeding with synchronous connections.
azerothcore-wotlk-ac-worldserver-1  | All connections on DatabasePool 'acore_playerbots' closed.
azerothcore-wotlk-ac-worldserver-1  | exit code: 1
azerothcore-wotlk-ac-worldserver-1  | worldserver terminated, restarting...
azerothcore-wotlk-ac-worldserver-1  | worldserver Terminated after 1 seconds, termination count: : 6
azerothcore-wotlk-ac-worldserver-1  | worldserver Restarter exited. Infinite crash loop prevented. Please check your system

**Comment by drachai** [comment]
In wordserver.conf 
SourceDirectory = "."    // correct this section according to your source

like c:/source

**Comment by Dreathean** [comment]
@CaspertheMighty Please close out this issue unless you are still experiencing it
