### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#148]
Hello Zheng!

When I activate this configuration, the server crashes as soon as it turns on, according to the GDB log below.

```
# Bots without a master will say their lines
AiPlayerbot.RandomBotSayWithoutMaster = 0 > 1
```

[gdb.txt](https://github.com/ZhengPeiRu21/mod-playerbots/files/10349372/gdb.txt)

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting this issue! Resolved in https://github.com/ZhengPeiRu21/mod-playerbots/commit/7c872915ec1e1ad6ab936233562771db1c6cd549.
