### ISSUE TITLE
tenth fail

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#15]
![Screenshot_2022-03-26-13-34-46-641_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160248971-6879dcaa-191b-4028-9fa8-d69de841d553.jpg)
![Screenshot_2022-03-26-13-34-56-667_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160248976-6d6a707b-596b-45ee-b129-6dc8109c6410.jpg)
![Screenshot_2022-03-26-13-35-09-138_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160248980-1b6db56b-a656-4169-b499-6fc0c38745d6.jpg)
![Screenshot_2022-03-26-13-35-17-705_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160248981-78a6d544-cf99-4181-9b65-cbae6b903ece.jpg)
![Screenshot_2022-03-26-13-35-32-929_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160248982-705efcaa-eeb4-4345-8c45-73e56e217b79.jpg)
![Screenshot_2022-03-26-13-35-44-446_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160248985-9829269c-ebe7-4948-8933-dca1aadd13f2.jpg)
![Screenshot_2022-03-26-13-35-52-007_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160248986-f98a1b40-fb86-4637-be89-4a43835be922.jpg)
![Screenshot_2022-03-26-13-36-13-845_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160248988-0e49c929-bb15-4200-961d-782a304b475e.jpg)

**Comment by ZhengPeiRu21** [comment]
This should be resolved with https://github.com/ZhengPeiRu21/mod-playerbots/commit/b3e3a13f5623becb0d0e6e49249299a5192bb6aa
