### ISSUE TITLE
worldserver crash

### ISSUE THREAD

**Issue by cjl3230** [ZhengPeiRu21/mod-playerbots#154]
mod-playerbots : https://github.com/ZhengPeiRu21/mod-playerbots 123ec85b86cfb0abf7104191b65b44707c071526
azerothcore:  https://github.com/ZhengPeiRu21/azerothcore-wotlk  ba4e49f5b24c

crash log
[ba4e49f5b24c_worldserver.exe_[12-2_0-51-10].txt](https://github.com/ZhengPeiRu21/mod-playerbots/files/10714178/ba4e49f5b24c_worldserver.exe_.12-2_0-51-10.txt)

**Comment by ZhengPeiRu21** [comment]
Thank you for the report and especially for submit the crash log! Fixed in https://github.com/ZhengPeiRu21/mod-playerbots/commit/d8ac42439a45aefa64f65f1b7c894885af3d419d.
