### ISSUE TITLE
The build can't completed

### ISSUE THREAD

**Issue by sd3420625** [ZhengPeiRu21/mod-playerbots#165]
I have done git clone the Playerbot branch, and replaced the mod in the modules folder. It show me errors when I rebuild the project:        arm64 ubuntu20.04

17 (find_package):
  Could not find a package configuration file provided by "boost_thread"
  (requested version 1.71.0) with any of the following names:

    boost_threadConfig.cmake
    boost_thread-config.cmake

  Add the installation prefix of "boost_thread" to CMAKE_PREFIX_PATH or set
  "boost_thread_DIR" to a directory containing one of the above files.  If
  "boost_thread" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/aarch64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  deps/boost/CMakeLists.txt:35 (find_package)

-- Configuring incomplete, errors occurred!
See also "/azerothcore/var/build/obj/CMakeFiles/CMakeOutput.log".

Is there anyone can help?

**Comment by Swdanylenko** [comment]
https://github.com/ZhengPeiRu21/mod-playerbots/issues/97#issuecomment-1256968334 fixed for me
i mean "opened ./apps/docker/Dockerfile in a text editor and add "libboost-thread-dev" (without quotes) to the three lines with other libboost stuff"

**Comment by Dreathean** [comment]
@sd3420625 please close out this issue unless you are still experiencing it with the latest update.
