### ISSUE TITLE
twelfth fail

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#17]
![Screenshot_2022-03-26-20-17-17-059_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160260258-4769dec6-38bb-48fe-8208-fc782d66d421.jpg)
![Screenshot_2022-03-26-20-18-00-744_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160260259-1e9d6770-ea55-484f-bdb4-133de8dbc5a0.jpg)
![Screenshot_2022-03-26-20-18-22-237_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160260260-f3cd5ddc-eadc-46ec-8191-cbe34618bd9e.jpg)
![Screenshot_2022-03-26-20-18-43-519_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160260262-8ac464ab-ad5e-43a4-be09-3c3c52838d7d.jpg)
![Screenshot_2022-03-26-20-19-02-723_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160260263-c8ff6055-6f46-4fe7-a31c-8824d5dd3787.jpg)
![Screenshot_2022-03-26-20-19-08-992_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160260264-6e3de670-1e18-4012-b550-c1bf5c06433a.jpg)
![Screenshot_2022-03-26-20-19-18-797_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160260265-603e0721-d2e7-4fd8-9eba-395f677190ae.jpg)
![Screenshot_2022-03-26-20-19-24-547_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160260266-48a05f05-efa0-4a19-a8a0-0351ce037bc2.jpg)

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-playerbots/commit/5c81a2d5e8d3d6f1552627f5bc7e37acb97dfdda
