### ISSUE TITLE
GetTargetIcon(int index) API changed to GetTargetIcons()[int index] 

### ISSUE THREAD

**Issue by xuanfeng66** [ZhengPeiRu21/mod-playerbots#175]
[631863c540.patch](https://github.com/ZhengPeiRu21/mod-playerbots/files/11074324/631863c540.patch)

**Comment by htc16** [comment]
@ZhengPeiRu21

**Comment by ZhengPeiRu21** [comment]
Fix applied in https://github.com/ZhengPeiRu21/mod-playerbots/commit/4abe553f2743f43e774a4c8f322398195afc7a32. 谢谢@xuanfeng66! ^_^

**Comment by htc16** [comment]
![image](https://user-images.githubusercontent.com/58153179/228327664-d7b917c1-831c-4c91-8cc6-52930f51c266.png)

from this last update we have an error that Group would not be declared.
I'm just trying to see here in the log which file is missing the statement

@ZhengPeiRu21

**Comment by ZhengPeiRu21** [comment]
Sorry, I should have checked this more thoroughly before committing the patch. I don't see why it is necessary to change this API - what is the reason for the patch?

**Comment by htc16** [comment]
actually, i even tried to check groups.h and it seems to me that there is no change in azerothcore source.

**Comment by ZhengPeiRu21** [comment]
> actually, i even tried to check groups.h and it seems to me that there is no change in azerothcore source.

Yes, I assumed this was a change to support a changed upstream API, but this is actually our own custom method to expose a normally private member needed by the bots, so this should not need to be changed.
