### ISSUE TITLE
Paladin AI tweek commit doesnt compiled successfully.

### ISSUE THREAD

**Issue by rogerc66** [ZhengPeiRu21/mod-playerbots#177]
Paladin AI tweek commit doesnt compiled successfully.

cmake complains about Sanctity aura is not declared or something like that.

**Comment by brian8544** [comment]
syntax error: identifier 'SanctityAuraTrigger'	@ modules\mod-playerbots\src\strategy\paladin\PaladinAiObjectContext.cpp	Line:146	--  static Trigger* sanctity_aura(PlayerbotAI* botAI) { return new SanctityAuraTrigger(botAI); }

**Comment by ZhengPeiRu21** [comment]
Thank you for the report! This should now be fixed in https://github.com/ZhengPeiRu21/mod-playerbots/commit/7d102f5434489214448855894b595c194720baf5.
