### ISSUE TITLE
BG Queue Crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#18]
![Screenshot_2022-03-26-22-11-05-123_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160262467-b5adf624-ae7a-4142-84e7-bdd5505ad1d6.jpg)
![Screenshot_2022-03-26-22-11-24-347_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160262469-ae1a47c4-851a-4a9a-bc61-c49d49cbd56f.jpg)
![Screenshot_2022-03-26-22-11-34-051_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160262470-ed82931d-d291-4b67-9ff8-720b8295ae89.jpg)
![Screenshot_2022-03-26-22-11-43-581_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160262471-aa9858e9-9045-41ce-8c6b-879e76cce125.jpg)
![Screenshot_2022-03-26-22-11-53-847_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160262474-374b5aff-aa51-4c1e-bae8-9313b2286231.jpg)

**Comment by htc16** [comment]
![Screenshot_2022-03-27-11-11-33-017_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160305467-99824b89-1e0b-4bef-bd63-10481f8d8189.jpg)
![Screenshot_2022-03-27-20-14-59-261_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160305473-c2505ae1-39ae-4489-a3a7-73972a366d00.jpg)
![Screenshot_2022-03-27-20-15-10-652_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160305475-973277bc-be74-4d9a-9181-ca93cfe67d84.jpg)
![Screenshot_2022-03-27-20-15-19-713_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160305477-c6921b5e-186b-46e5-b2ba-e75921466782.jpg)
![Screenshot_2022-03-27-20-15-39-476_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160305480-1f136588-9379-4e62-9456-c529c0f24d39.jpg)
![Screenshot_2022-03-27-20-16-39-484_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160305482-38db7880-caf3-4e22-ac71-a5af84ff7700.jpg)
![Screenshot_2022-03-27-20-16-45-877_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160305485-0d230478-b749-4a1f-bc43-452b98198366.jpg)
![Screenshot_2022-03-27-20-16-52-674_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160305487-be1c8f69-765c-4fcf-ab2f-80b6d6ff8a11.jpg)

**Comment by htc16** [comment]
![Screenshot_2022-03-28-15-46-21-755_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160466134-35a18426-a944-439d-afe2-5755c17ea4fe.jpg)
![Screenshot_2022-03-28-15-46-38-904_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160466157-7af23536-00cd-4a93-b3c0-f381c941cfde.jpg)
![Screenshot_2022-03-28-15-46-50-599_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160466175-4e4465ba-ea1a-4ad2-876b-dd50984fd67c.jpg)
![Screenshot_2022-03-28-15-47-00-224_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160466192-3082bbc3-4959-48b0-b70d-1dfcdc902242.jpg)
![Screenshot_2022-03-28-15-47-05-887_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160466280-c6bcaebc-2bde-461b-be79-d28197a47548.jpg)
![Screenshot_2022-03-28-15-47-11-495_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160466305-45b056a2-4673-41a9-b55e-6c40a45ed16e.jpg)

**Comment by ZhengPeiRu21** [comment]
Hopefully resolved with https://github.com/ZhengPeiRu21/mod-playerbots/commit/16ef20cd3e23aa38d4c373ff6a0fe991199ff69b
