### ISSUE TITLE
ASSERTION FAILED

### ISSUE THREAD

**Issue by Greyisttot** [ZhengPeiRu21/mod-playerbots#186]
>ASSERTION FAILED
Location '/0/1 source/src/server/game/Chat/Chat.cpp:253'
Function 'BuildChatPacket'
Condition 'channelName.length ()>0'

**Comment by Greyisttot** [comment]
Ubuntu 22.04.2 LTS x86_64(Py3.7.8) MYSQL8.0.32

**Comment by Greyisttot** [comment]
This problem has existed for almost half a year. If you enable the random robot, it will automatically crash and restart, and if you disable the random robot, it will start normally.

**Comment by Greyisttot** [comment]
Has been resolved, is the use of Chinese DBC caused by the problem.

**Comment by Greyisttot** [comment]
ChatChannels.dbc

**Comment by Dreathean** [comment]
@Greyisttot please close this as you say you have resolved the issue
