### ISSUE TITLE
Compile Error: modules and worldserver failed

### ISSUE THREAD

**Issue by dswkfi48** [ZhengPeiRu21/mod-playerbots#195]
Have seemingly done all correct steps, after cleaning and attempting to build I in VS2022 I get:

22>Done building project "modules.vcxproj" -- FAILED.
25>------ Build started: Project: worldserver, Configuration: RelWithDebInfo x64 ------
25>Building Custom Rule F:/Games/WoW/_Setup/AzerothCore/azerothcore-wotlk/src/server/apps/CMakeLists.txt
25>cmake_pch.cxx
25>Main.cpp
25>ACSoap.cpp
25>CliRunnable.cpp
25>RASession.cpp
25>WheatyExceptionReport.cpp
25>ServiceWin32.cpp
25>LINK : fatal error LNK1181: cannot open input file '..\..\..\modules\RelWithDebInfo\modules.lib'
25>Done building project "worldserver.vcxproj" -- FAILED.
26>------ Build started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------
26>Building Custom Rule F:/Games/WoW/_Setup/AzerothCore/azerothcore-wotlk/CMakeLists.txt
========== Build: 24 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 3:47 PM and took 18:17.160 minutes ==========

**Comment by wushiwein119** [comment]
https://github.com/ZhengPeiRu21/mod-playerbots/pull/190

**Comment by dswkfi48** [comment]
> #190

I just tried his version and it still failed with the exact same statements.

Never mind! I didn't correclty implement the pull request. #190 fixes the issue. Thank you wushiwein for your help.
