### ISSUE TITLE
wont complile

### ISSUE THREAD

**Issue by Griptor** [ZhengPeiRu21/mod-playerbots#196]
using the latest custom branch and latest mod.

Severity	Code	Description	Project	File	Line	Suppression State

Error	C2039	'type': is not a member of 'LFGDungeonEntry'	modules	D:\CustomWow\Azerothcore\ZhengPeiRu21\azerothcore-wotlk\modules\mod-playerbots\src\strategy\actions\LfgActions.cpp	103
	
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'minlevel': is not a member of 'LFGDungeonEntry'	modules	D:\CustomWow\Azerothcore\ZhengPeiRu21\azerothcore-wotlk\modules\mod-playerbots\src\strategy\actions\LfgActions.cpp	107	

lines 113, 174, 343,350

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file '..\..\..\modules\RelWithDebInfo\modules.lib'	worldserver	D:\CustomWow\_builds\src\server\apps\LINK	1	

fingers crossed i can play soon i for got to back up lol thanx guys !
best of luck :D

**Comment by godlike73** [comment]
Same problem here too, wont build anymore after fresh install

**Comment by erickl979** [comment]
Same.  I removed the LFGActions files.  Then I used /find to locate all locations where LFGActions was used in the file WorldPacketActionContext.h

The compile will complete and the game runs fine.  The bot's will never select a roll if you use LFG though.

But it does work with the changes.

**Comment by godlike73** [comment]
My fix was to use one of the pull requesters cloned repo compiled and works fine with it until the changes get merged ;)
git clone https://github.com/Embracefate989/mod-playerbots.git --branch patch-1

**Comment by godlike73** [comment]
I think something changed in the master of the main azerothcore becuase with the playerbot branch alot of addons will not compile anymore including playerbots.

**Comment by Griptor** [comment]
I  got it to compile without solocraft or autobalance. 
This hasn't been updated for so long :(
I just want the bots to do stuff in bgs and join in dungeons and i would be soo much happy lol

**Comment by godlike73** [comment]
Ya it compiles if u only use playerbots, but solocraft autobalance eluna and a few others that i tried will fail

**Comment by Dreathean** [comment]
@Griptor This should be fixed with the latest updates, please confirm and close out if resolved.

**Comment by Griptor** [comment]
Yes is fixed :)
