### ISSUE TITLE
Bot funkiness: quests and combat

### ISSUE THREAD

**Issue by amolokruo** [ZhengPeiRu21/mod-playerbots#197]
Not sure if anybody else is experiencing this, but bots just behave weirdly.

Big issue is in combat. Warriors/melee combat bots will immediately teleport to or lag-walk to (while facing away from) the mob. Casting classes never get their spells off. Warlock spams shadow bolt but it never fully casts, then it restarts the cast, and so the bot never deals any damage.

Another issue is with quests: while using the addon created by the willow person, getting a bot to talk to or accept a quest from a quest giver is finicky. Sometimes a bot won’t accept a quest if there are multiple being given (it will accept the first one only) and needs to be told to accept all quests multiple times for it to actually accept it(posting this here because I assume this not to be an issue of the add on but of the module itself). Side question: are bots scripted to automatically search for and take quest loot off of mobs? Mine don’t do that for some reason. 

I would like any input on if this is the current state of the module or if it is just me having these issues.
Thank you!

**Comment by HPJones** [comment]
I have the same issue

**Comment by ZhengPeiRu21** [comment]
These issues are unfortunately just the state of the module at the moment; it is not a problem with your installation. The module is still in relatively early development.

**Comment by htc16** [comment]
@liyunfan1223 Worked with some updates, including your bot module already use the talent tree. I think @ZhengPeiRu21 could care and work together for even greater progress.

**Comment by htc16** [comment]
The only point I noticed in @liyunfan1223 playerbots mod is that he still doesn't fly and doesn't use boats, otherwise they go to the player and play normally in a party for example.

**Comment by htc16** [comment]
![image](https://github.com/ZhengPeiRu21/mod-playerbots/assets/58153179/cf57c849-2ae3-413f-854a-0e7233bc82a8)

![image](https://github.com/ZhengPeiRu21/mod-playerbots/assets/58153179/4bdc8b9e-928a-4f1a-9c5d-60749aad0be3)

it is even possible to play DG with the bots.

**Comment by htc16** [comment]
still, what i could notice about the boats and flights, when ultranix imported the playerbots AI from Celguar (https://github.com/celguar/mangosbot-bots/tree/1837718aa01d97f5e71477d48a164aaf089a40ee)
this system of boats and flights was still under development.
What I could see is that the boat and flight functions came in later versions, that is, it would be necessary @ZhengPeiRu21 or @liyunfan1223 to start importing and adapting new versions to be able to see the bots traveling using boats.
the functions of boats and flights are commented in TravelMgr.cpp (https://github.com/celguar/mangosbot-bots/blob/1837718aa01d97f5e71477d48a164aaf089a40ee/playerbot/TravelMgr.cpp) and only came after updates.

**Comment by Dreathean** [comment]
> Not sure if anybody else is experiencing this, but bots just behave weirdly.
> 
> Big issue is in combat. Warriors/melee combat bots will immediately teleport to or lag-walk to (while facing away from) the mob. Casting classes never get their spells off. Warlock spams shadow bolt but it never fully casts, then it restarts the cast, and so the bot never deals any damage.
> 
> Another issue is with quests: while using the addon created by the willow person, getting a bot to talk to or accept a quest from a quest giver is finicky. Sometimes a bot won’t accept a quest if there are multiple being given (it will accept the first one only) and needs to be told to accept all quests multiple times for it to actually accept it(posting this here because I assume this not to be an issue of the add on but of the module itself). Side question: are bots scripted to automatically search for and take quest loot off of mobs? Mine don’t do that for some reason.
> 
> I would like any input on if this is the current state of the module or if it is just me having these issues. Thank you!

I believe most of these issues have been resolved by the latest updates, please verify and confirm and close so we can clear out these old issues. The quests portion may not be fully implemented yet however the combat issues have been improved tremendously

@htc16 I think maybe you should open a new issue for the zeppelin/boat specifically?

**Comment by amolokruo** [comment]
> > Not sure if anybody else is experiencing this, but bots just behave weirdly.
> > Big issue is in combat. Warriors/melee combat bots will immediately teleport to or lag-walk to (while facing away from) the mob. Casting classes never get their spells off. Warlock spams shadow bolt but it never fully casts, then it restarts the cast, and so the bot never deals any damage.
> > Another issue is with quests: while using the addon created by the willow person, getting a bot to talk to or accept a quest from a quest giver is finicky. Sometimes a bot won’t accept a quest if there are multiple being given (it will accept the first one only) and needs to be told to accept all quests multiple times for it to actually accept it(posting this here because I assume this not to be an issue of the add on but of the module itself). Side question: are bots scripted to automatically search for and take quest loot off of mobs? Mine don’t do that for some reason.
> > I would like any input on if this is the current state of the module or if it is just me having these issues. Thank you!
> 
> I believe most of these issues have been resolved by the latest updates, please verify and confirm and close so we can clear out these old issues. The quests portion may not be fully implemented yet however the combat issues have been improved tremendously
> 
> @htc16 I think maybe you should open a new issue for the zeppelin/boat specifically?

I am away from my computer at college now so I won't be able to verify until ~ December 10.
Will do ASAP when able.
