### ISSUE TITLE
Second Crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#2]
Hello, by cell phone I updated the mod and presented me with a new crash then

![Screenshot_2022-03-23-14-25-25-422_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159759621-389a7869-d72e-4e0d-9f12-25a1b87dc07b.jpg)

If the photos don't help with the size, as soon as I get home I'll upload a larger photo.

Note: I didn't update the font, is it necessary?

**Comment by ZhengPeiRu21** [comment]
This should be resolved in https://github.com/ZhengPeiRu21/mod-playerbots/commit/d31fc287afd1f67f97e0b86820f9779bc281b4f1. Please notice if you still see any issues!
