### ISSUE TITLE
Online Players

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#20]
After a normal player goes online, after he logs out the character it still remains as online in the table.

**Comment by Greyisttot** [comment]
Mir2 online hang up bubble point?😅

**Comment by whipowill** [comment]
I can confirm that bots are left marked "logged in" in the database even though you the player have logged out.  I also am having issues where I want to invite a bot to my party but it says they are already in one.  Doing a ``.group disband BOTNAME" doesn't solve the issue.  Logging out and back in as that bot character show they are not in a party.

**Comment by whipowill** [comment]
I saw a chat on Discord for Cmangos where a playerbots user reported this same issue of being unable to invite bots due to "already in a group" -- so I think that means it must be a problem with the playerbots module.

**Comment by whipowill** [comment]
I was able to fix this by doing a GM ``.die`` command on the character.  Then I made sure my own party was disbanded.  Then when he resurrected I invited him and it worked.  I have no idea how or why this worked but this is what the guy in the Mangos discord said to do and it worked for me.
