### ISSUE TITLE
关于sScriptMgr->OnAfterPlayerUpdate

### ISSUE THREAD

**Issue by netweaver** [ZhengPeiRu21/mod-playerbots#204]
抱歉，在https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbot 无法提交issue，所以把问题提到这里来了
在上述分支里的src/server/game/Entities/Player/PlayerUpdates.cpp文件中发现了sScriptMgr->OnAfterPlayerUpdate的调用，而没有找到该函数的定义和实现，这行代码是在96960d提交（从master合并到playerbot分支）时加入的，但是从master中无法找到该行代码，比较奇怪。
我是在azerothcore-wotlk合并了npcbots后又来合并您这边的playerbots时，正好PlayerUpdate.cpp有冲突需要解决才无意间发现的，因为找不到该函数的具体实现，不知道合并进去是否会造成问题，所以来请教一下。

**Comment by garfieldz90** [comment]
应该不会影响

> 抱歉，在https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbot 无法提交issue，所以把问题提到这里来了 在上述分支里的src/server/game/Entities/Player/PlayerUpdates.cpp文件中发现了sScriptMgr->OnAfterPlayerUpdate的调用，而没有找到该函数的定义和实现，这行代码是在96960d提交（从master合并到playerbot分支）时加入的，但是从master中无法找到该行代码，比较奇怪。 我是在azerothcore-wotlk合并了npcbots后又来合并您这边的playerbots时，正好PlayerUpdate.cpp有冲突需要解决才无意间发现的，因为找不到该函数的具体实现，不知道合并进去是否会造成问题，所以来请教一下。

能成功编译吗？

**Comment by netweaver** [comment]
后来写新增hook给eluna用，仔细看了才知道只是个虚函数，在eluna等全天mod中实现用的。 所以不是问题，关闭了
