### ISSUE TITLE
编译报错 我这个步骤哪里有问题啊 能不能出一个中文的安装教程

### ISSUE THREAD

**Issue by dancheng9999** [ZhengPeiRu21/mod-playerbots#210]
cd /wow/

wget https://github.com/ZhengPeiRu21/azerothcore-wotlk/archive/refs/heads/Playerbot.zip

unzip

mv azerothcore-wotlk-Playerbot azerothcore-wotlk

wget https://github.com/ZhengPeiRu21/mod-playerbots/archive/AzerothCore.zip

unzip

mv mod-playerbots-AzerothCore /wow/azerothcore-wotlk/modules

./acore.sh docker build
...
/usr/bin/ld: ../../../modules/libmodules.a(ModulesLoader.cpp.o): in function AddModulesScripts()': /azerothcore/var/build/obj/modules/gen_scriptloader/static/ModulesLoader.cpp:53: undefined reference to Addmod_playerbots_AzerothCoreScripts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/apps/CMakeFiles/worldserver.dir/build.make:177: src/server/apps/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1086: src/server/apps/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by garfieldz90** [comment]
兄弟,你第一个安装包是拉的哪个？

**Comment by garfieldz90** [comment]
> cd /wow/
> 
> wget https://github.com/ZhengPeiRu21/azerothcore-wotlk/archive/refs/heads/Playerbot.zip
> 
> unzip
> 
> mv azerothcore-wotlk-Playerbot azerothcore-wotlk
> 
> wget https://github.com/ZhengPeiRu21/mod-playerbots/archive/AzerothCore.zip
> 
> unzip
> 
> mv mod-playerbots-AzerothCore /wow/azerothcore-wotlk/modules
> 
> ./acore.sh docker build ... /usr/bin/ld: ../../../modules/libmodules.a(ModulesLoader.cpp.o): in function AddModulesScripts()': /azerothcore/var/build/obj/modules/gen_scriptloader/static/ModulesLoader.cpp:53: undefined reference to Addmod_playerbots_AzerothCoreScripts()' clang: error: linker command failed with exit code 1 (use -v to see invocation) make[2]: *** [src/server/apps/CMakeFiles/worldserver.dir/build.make:177: src/server/apps/worldserver] Error 1 make[1]: *** [CMakeFiles/Makefile2:1086: src/server/apps/CMakeFiles/worldserver.dir/all] Error 2 make: *** [Makefile:130: all] Error 2

我的步骤就是先拉azerothcore `git clone https://github.com/ZhengPeiRu21/azerothcore-wotlk.git --branch=Playerbot`,
在cd进去module下，`git clone https://github.com/ZhengPeiRu21/mod-playerbots.git`, 在回到azerothcore目录下'mkdir build', 然后进入build在使用官方的教程https://www.azerothcore.org/wiki/linux-core-installation , 输入`cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static`,其中$HOME就是你/home/你的账户名称,至于clang的版本要看你系统里安装的是什么版本。最后make && make install

**Comment by garfieldz90** [comment]
docker安装我没用过，不知道如何做。

**Comment by dancheng9999** [comment]
> docker安装我没用过，不知道如何做。
你编译成功了吗？我拉的是作者推荐的那个

**Comment by garfieldz90** [comment]
> docker安装我没用过，不知道如何做。
> 你编译成功了吗？我拉的是作者推荐的那个

肯定成功呀，我是按照我上面的方法做的，按着官方教程走的https://www.azerothcore.org/wiki/installation#azerothcore-classic-setup

**Comment by dancheng9999** [comment]
> > docker安装我没用过，不知道如何做。
> > 你编译成功了吗？我拉的是作者推荐的那个
> 
> 肯定成功呀，我是按照我上面的方法做的，按着官方教程走的https://www.azerothcore.org/wiki/installation#azerothcore-classic-setup

成功了谢谢大兄弟
