### ISSUE TITLE
Errors when starting world server

### ISSUE THREAD

**Issue by Wishmaster117** [ZhengPeiRu21/mod-playerbots#211]
When starting world server i have this error:

Script named 'npc_kalecgos' is not assigned in the database.
Script named 'npc_fiendish_imp' is assigned in the database, but has no code!
Script named 'npc_fiendish_portal' is assigned in the database, but has no code!

I used https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbot and https://github.com/ZhengPeiRu21/mod-playerbots to compile.

Can someone help?

**Comment by ZhengPeiRu21** [comment]
This is not related to the module. This is caused by your database and core versions not being in sync - please ensure you are running the latest core and the latest SQL updates.
