### ISSUE TITLE
能不能出一个不修改 azerothcore-wotlk 源码的版本

### ISSUE THREAD

**Issue by papwuj** [ZhengPeiRu21/mod-playerbots#217]
大佬好，能不能出一个不修改 azerothcore-wotlk 源码的版本，否则每次更新代码会很麻烦~！

**Comment by garfieldz90** [comment]
> 大佬好，能不能出一个不修改 azerothcore-wotlk 源码的版本，否则每次更新代码会很麻烦~！

兄弟,如果你去看过源码你就明白很难，原核心里面很多方法的调用是需要自定义加进去一些方法的，我也试过了，不太行得通。

**Comment by papwuj** [comment]
感谢大佬解答~~
