### ISSUE TITLE
Complie errors

### ISSUE THREAD

**Issue by youhuowa** [ZhengPeiRu21/mod-playerbots#22]
lastest playerbot azerothcore branch and mod-playerbots

win11 wsl ubuntu 20.04

azerothcore-wotlk/modules/mod-playerbots/src/GuildTaskMgr.cpp:504:5: fatal error: unkn                                                                                                                                                 own type name 'PlayerbotsDatabasePreparedStatement'; did you mean 'CharacterDatabasePrepared                                                                                                                                                 Statement'?
    PlayerbotsDatabasePreparedStatement* stmt = PlayerbotsDatabase.GetPreparedStatement(PLAY                                                                                                                                                 ERBOTS_SEL_GUILD_TASKS_BY_VALUE);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CharacterDatabasePreparedStatement

/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotDbStore.cpp:14:5: fatal error: u                                                                                                                                                 nknown type name 'PlayerbotsDatabasePreparedStatement'; did you mean 'CharacterDatabasePrepa                                                                                                                                                 redStatement'?
    PlayerbotsDatabasePreparedStatement* stmt = PlayerbotsDatabase.GetPreparedStatement(PLAY                                                                                                                                                 ERBOTS_SEL_DB_STORE);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CharacterDatabasePreparedStatement

[ 74%] Linking CXX static library libscripts.a
[ 74%] Built target scripts
make: *** [Makefile:130: all] Error 2

real    9m54.473s
user    45m47.109s
sys     27m10.750s

**Comment by ZhengPeiRu21** [comment]
Thank you for report. You are the second user to see this issue, but most do not see it. Would you please try this fix and let me know if it is resolve:

In modules/CMakeLists.txt, please change line 87 from `if (SOURCE_MODULE MATCHES "mod-playerbots")` to `if (SOURCE_MODULE MATCHES "mod_playerbots")` - replacing the "-" with "_".

**Comment by youhuowa** [comment]
I used the original azerothcore cmakelists.txt file to compile, which was accidentally copied to the modules fold when I copied my old server's modules to the new playerbots branch...

But now I have the same issue as issue #14

/azerothcore-wotlk/modules/mod-playerbots/src/strategy/actions/MovementActions.cpp:304:40: fatal error: use of overloaded operator '!=' is ambiguous (with operand types 'WorldPosition' and 'WorldPosition')
                if (telePos && telePos != movePosition)
                               ~~~~~~~ ^  ~~~~~~~~~~~~
cmake version 3.16.3
clang version 10.0.0-4ubuntu1
