### ISSUE TITLE
Autobalance and Playerbots - Worldserver crashing when pressing 'Enter Battle' on battleground notification

### ISSUE THREAD

**Issue by SheriffBaloo** [ZhengPeiRu21/mod-playerbots#222]
Autobalance (ZhengPeiRu21's fork) being added is crashing my battlegrounds when clicking 'Enter Battle' on the battleground queue notification after about 3 seconds of very high lag, no loading screen after clicking 'Enter Battle' shows up, just unable to cast for about 3 seconds and then my worldserver crashes. 

[b739cfe21960+_worldserver.exe_[29-11_0-54-50].dmp](https://github.com/ZhengPeiRu21/mod-playerbots/files/13497129/b739cfe21960%2B_worldserver.exe_.29-11_0-54-50.dmp)
[b739cfe21960+_worldserver.exe_[29-11_0-54-50].txt](https://github.com/ZhengPeiRu21/mod-playerbots/files/13497131/b739cfe21960%2B_worldserver.exe_.29-11_0-54-50.txt)
[Auth.log](https://github.com/ZhengPeiRu21/mod-playerbots/files/13497133/Auth.log)
[Errors.log](https://github.com/ZhengPeiRu21/mod-playerbots/files/13497135/Errors.log)
[Playerbots.log](https://github.com/ZhengPeiRu21/mod-playerbots/files/13497136/Playerbots.log)
[Server.log](https://github.com/ZhengPeiRu21/mod-playerbots/files/13497139/Server.log)

**Comment by Dreathean** [comment]
I don't believe Autobalance is really intended or planned to be used with Playerbots, it's supposed to be used for smaller groups of people whereas Playerbots is also supposed to fill the same gap. However there is a functional Autobalance fork for NPCBots if you want to try using that.

**Comment by SheriffBaloo** [comment]
Sorry if this is annoying but could you link it to me. I am still not 100% sure how to navigate GitHub. And who’s the fork by? I am using Jack’s one (username includes it) and it now lets me into bgs but will crash about 7 minutes into the battleground.

**Comment by Dreathean** [comment]
No worries. Trickerer's NPCbot fork for autobalance is here: 
https://github.com/trickerer/mod-autobalance
And the NPCbots for Azerothcore is here:
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots
With more info here:
https://github.com/trickerer/Trinity-Bots

But again, this is only for NPCbots which is totally different from Playerbots.

**Comment by SheriffBaloo** [comment]
Ah okay thank you very much! I am not too set on using NPCBots as I mainly want this as a tool to complete raids with your alts being involved at the same time, almost like an RTS but you can play without the alts if you'd like to do something on just that char.
