### ISSUE TITLE
New Crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#23]
![image](https://user-images.githubusercontent.com/58153179/161096886-a7dc85b5-effc-45c2-b1a0-539d55cf4cbb.png)
![image](https://user-images.githubusercontent.com/58153179/161096984-1e162a5b-c5c0-4d2a-820c-8008df172a29.png)

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-playerbots/commit/57e9c81575ac13d9336d2cc38802b7182a4ee7ba
