### ISSUE TITLE
error: ‘class Group’ has no member named ‘GetTargetIcon’; did you mean ‘SetTargetIcon’?

### ISSUE THREAD

**Issue by Greyisttot** [ZhengPeiRu21/mod-playerbots#24]
In file included from /acsource/modules/mod-playerbots/src/strategy/Action.h:11,
                 from /acsource/modules/mod-playerbots/src/strategy/Strategy.h:8,
                 from /acsource/modules/mod-playerbots/src/strategy/AiObjectContext.h:11,
                 from /acsource/modules/mod-playerbots/src/Playerbots.h:8,
                 from /acsource/modules/mod-playerbots/src/ChatFilter.cpp:7:
/acsource/modules/mod-playerbots/src/strategy/Value.h: In member function ‘T CalculatedValue<T>::Get()’:
/acsource/modules/mod-playerbots/src/strategy/Value.h:58:142: warning: invalid use of incomplete type ‘class AiObjectContext’
   58 | tart(PERF_MON_VALUE, this->getName(), this->context ? &this->context->performanceStack : nullptr);
      |                                                                     ^~

In file included from /acsource/modules/mod-playerbots/src/strategy/Action.h:8,
                 from /acsource/modules/mod-playerbots/src/strategy/Strategy.h:8,
                 from /acsource/modules/mod-playerbots/src/strategy/AiObjectContext.h:11,
                 from /acsource/modules/mod-playerbots/src/Playerbots.h:8,
                 from /acsource/modules/mod-playerbots/src/ChatFilter.cpp:7:
/acsource/modules/mod-playerbots/src/strategy/AiObject.h:11:7: note: forward declaration of ‘class AiObjectContext’
   11 | class AiObjectContext;
      |       ^~~~~~~~~~~~~~~
/acsource/modules/mod-playerbots/src/ChatFilter.cpp: In member function ‘virtual const string RtiChatFilter::Filter(std::string&)’:
/acsource/modules/mod-playerbots/src/ChatFilter.cpp:166:47: error: ‘class Group’ has no member named ‘GetTargetIcon’; did you mean ‘SetTargetIcon’?
  166 |                 ObjectGuid rtiTarget = group->GetTargetIcon(RtiTargetValue::GetRtiIndex(rti.substr(1)));
      |                                               ^~~~~~~~~~~~~
      |                                               SetTargetIcon
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:934: modules/CMakeFiles/modules.dir/mod-playerbots/src/ChatFilter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1237: modules/CMakeFiles/modules.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by htc16** [comment]
You're just not using the playerbot branch.
