### ISSUE TITLE
New BG crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#25]
the bots do not enter the BG and after a while the server goes down

![image](https://user-images.githubusercontent.com/58153179/161169039-a185eaf8-bb6d-4e0a-89dd-e530433f3ef4.png)
![image](https://user-images.githubusercontent.com/58153179/161169064-ef849479-b721-49fc-b9f6-abc4f0c83c33.png)
![image](https://user-images.githubusercontent.com/58153179/161169099-3446e78a-671b-4556-97e7-7b07bc7a9117.png)
![image](https://user-images.githubusercontent.com/58153179/161169130-4ab7524e-dba1-4543-bae5-b6e78f70e226.png)

**Comment by ZhengPeiRu21** [comment]
Hopeful resolved in https://github.com/ZhengPeiRu21/mod-playerbots/commit/dbb80b6aa22f3a21bf94645c84e49af9db3edc52
