### ISSUE TITLE
New Crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#27]
![Screenshot_2022-04-01-23-28-32-520_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362314-53050c2e-6815-4332-9d9a-2693f58259ed.jpg)
![Screenshot_2022-04-01-23-28-46-448_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362319-58731737-135d-4351-87ae-dba0189e0b8a.jpg)
![Screenshot_2022-04-01-23-28-55-175_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362321-1d0c7fc3-f261-4773-bca7-a8b9146544ef.jpg)
![Screenshot_2022-04-01-23-29-08-335_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362323-03beec48-8764-492f-baf5-8d4323cd849c.jpg)
![Screenshot_2022-04-01-23-29-19-398_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362324-68b71062-0f2f-448b-86b3-dfeb50eaf2ce.jpg)
![Screenshot_2022-04-01-23-29-35-156_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362326-e4269d0c-fea4-4da1-bd3c-a36eb4d0376d.jpg)
![Screenshot_2022-04-01-23-29-45-985_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362327-939d844d-ac7b-4de5-b8ec-2aa96fe7fe73.jpg)
![Screenshot_2022-04-01-23-29-54-529_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362329-36953f3e-5afb-40b2-bfe3-7009ee1fcb12.jpg)
![Screenshot_2022-04-01-23-30-01-868_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362332-3a7939cc-215a-4fc6-8b9d-62f414b6f4e6.jpg)
![Screenshot_2022-04-01-23-30-09-101_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362334-56e3542a-902a-49f9-a447-d6c1e12058a7.jpg)
![Screenshot_2022-04-01-23-30-15-884_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362335-57049b5f-b45b-4c42-8fd3-708f7b0175de.jpg)
![Screenshot_2022-04-01-23-30-21-440_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362336-09b3a843-dbc5-4abb-b1f0-5ed198a00a33.jpg)
![Screenshot_2022-04-01-23-30-28-636_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161362337-bba67aae-0482-4bd7-9340-f0fcf144da7b.jpg)

**Comment by biancong1208** [comment]
I have been failing to compile for days. #9

**Comment by ZhengPeiRu21** [comment]
Would you please try after commit https://github.com/ZhengPeiRu21/mod-playerbots/commit/8f5be075b4875b5b4a9bba141ac127f88e6f05cd to see if this issue is resolve?

**Comment by htc16** [comment]
This is not the type of failure that happens all the time, so much so that my server has been connected for more than 1 day without crashing, so I think we can close this issue and I reopen it again, ok?
