### ISSUE TITLE
third crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#3]
![image](https://user-images.githubusercontent.com/58153179/159798293-54d56296-2a21-4a34-ba9d-c5333b8653a4.png)

Note: I still have the outdated font, I just updated the mod.

**Comment by ZhengPeiRu21** [comment]
Thank you for the reporting. This should be fixed in https://github.com/ZhengPeiRu21/mod-playerbots/commit/bce32cc0e884a6176f2795ca736f74091a5c2a6b. Please let me know if you still see issue after that commit.
