### ISSUE TITLE
Which version of Azeroth Core-Wotlk is required for this model Can be used normally

### ISSUE THREAD

**Issue by 250cn** [ZhengPeiRu21/mod-playerbots#32]
Which version of Azeroth Core-Wotlk is required for this model Can be used normally, can you provide a core link.

**Comment by Bogir** [comment]
module development is in progress and is not stable and can't be used normally.
For now it requires many custom changes in the core.

You can help to develop it using this repo and 
https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbothttps://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbot
