### ISSUE TITLE
N Crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#33]

**Comment by htc16** [comment]
![Screenshot_2022-04-06-06-45-30-688_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948281-d708f704-1d68-4b4f-b948-7ce65a12b510.jpg)
![Screenshot_2022-04-06-06-45-44-676_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948293-1840eb38-4a75-440d-b87b-5bcf94e32f17.jpg)
![Screenshot_2022-04-06-06-45-57-013_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948294-ee157837-3568-415f-ac72-dc48a934d48e.jpg)
![Screenshot_2022-04-06-06-46-09-531_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948303-b4c39268-6485-400e-b284-149d2a8768ed.jpg)
![Screenshot_2022-04-06-06-46-18-081_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948308-c8a7c575-1633-4c63-a20d-bb9728f46155.jpg)
![Screenshot_2022-04-06-06-46-29-651_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948314-426d42f9-be65-40e9-8e2d-955869f877fd.jpg)
![Screenshot_2022-04-06-06-46-45-495_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948326-b13fa963-add9-44bf-83ee-b4aadc89c04a.jpg)
![Screenshot_2022-04-06-06-46-55-562_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948332-7b82c26a-4cc5-4337-90d1-9bcf0c18f9ed.jpg)
![Screenshot_2022-04-06-06-47-02-489_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948341-5662e2ac-d054-4f70-9651-468cc8336dca.jpg)
![Screenshot_2022-04-06-06-47-11-135_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948349-85b7e324-8591-4d95-8304-089fed9eda4b.jpg)
![Screenshot_2022-04-06-06-47-18-865_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948362-fc5196ed-d109-49c8-9954-e7fab0e80299.jpg)
![Screenshot_2022-04-06-06-47-26-728_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948373-6334ba40-f295-4bb7-a501-651492992d86.jpg)
![Screenshot_2022-04-06-06-47-38-588_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/161948391-3eeb4c2f-e455-4812-b990-fc9a8e8ced20.jpg)

**Comment by ZhengPeiRu21** [comment]
This should be resolved in https://github.com/ZhengPeiRu21/mod-playerbots/commit/e7c3b474d3c29ee2278718ab7c84b09aa9635259. Please note I have disabled knockback processing for bots for now until this can be properly fix.
