### ISSUE TITLE
2022/04/06 progress

### ISSUE THREAD

**Issue by biancong1208** [ZhengPeiRu21/mod-playerbots#34]
Successfully compiled and entered the game.
The following problems occur:
1.The worldserver process is terminated within a very short time (5min) after it is started.
![image](https://user-images.githubusercontent.com/93648230/161991805-089e9403-2257-4064-bcef-a6fcb664c1fe.png)

2.There are many high-level playerbots in the birthplace, it is recommended to be distributed in the matching area according to the level.

**Comment by ZhengPeiRu21** [comment]
Thank you for report this issue. Are you using Chinese locale? This may be related to the crash. I will investigate.

**Comment by biancong1208** [comment]
> Thank you for report this issue. Are you using Chinese locale? This may be related to the crash. I will investigate.

YES,Chinese locale.

thank you very much.
