### ISSUE TITLE
Bot stop move bug

### ISSUE THREAD

**Issue by rogerc66** [ZhengPeiRu21/mod-playerbots#37]
one interesting thing observed, sometimes after a decent combat, bot low on health, they will recover themself by consuming food, after fully recovered, they will standing still forever, although they still say their lines to respond your commands, but they wont move at all.

**Comment by thepopdog** [comment]
I noticed that this occurs more often with casters and hunters, possibly others. Melee classes seem unaffected. Paladins are 50% affected. Might possibly be related to the spell loop error observed in the server output console.

**Comment by Dreathean** [comment]
@rogerc66 per the above merges I believe this has been largely improved if you can please close this issue out
