### ISSUE TITLE
NEW CRASH

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#39]
![Screenshot_2022-04-08-15-33-29-338_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/162501426-f26fbf7f-8b74-478c-a41e-f0ee6bca35af.jpg)
![Screenshot_2022-04-08-15-33-37-423_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/162501438-df7ddbff-c8d5-484e-8af0-162841c8ea0d.jpg)
![Screenshot_2022-04-08-15-33-44-432_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/162501449-4935cef1-dd59-433e-bfc4-d941c933bd8d.jpg)
![Screenshot_2022-04-08-15-33-52-149_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/162501457-f1b6e155-d4b1-4d35-b350-4c47965f8465.jpg)
![Uploading Screenshot_2022-04-08-15-33-57-876_com.server.auditor.ssh.client.jpg…]()

**Comment by Greyisttot** [comment]
fighting👍

**Comment by ZhengPeiRu21** [comment]
Hopefully fixed with https://github.com/ZhengPeiRu21/mod-playerbots/commit/c9e8799392145fca17409d3eafe094619a9a5f04
