### ISSUE TITLE
fourth fall

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#4]
**First time**
![image](https://user-images.githubusercontent.com/58153179/159812727-36584d88-d0b6-4a35-95df-9c60d3a06e5d.png)
![image](https://user-images.githubusercontent.com/58153179/159812777-ade5b7c3-c1fb-448c-8c48-4f27db31841f.png)
![image](https://user-images.githubusercontent.com/58153179/159812836-2d460e29-69d0-44d2-93b3-410ad5da432e.png)

**Second time**
![image](https://user-images.githubusercontent.com/58153179/159821200-fec4ed9b-8e6d-4c4b-8fcb-88e2ac8a959e.png)
![image](https://user-images.githubusercontent.com/58153179/159821233-aa9990cc-7cb5-4725-98bc-05f1bb2df029.png)
![image](https://user-images.githubusercontent.com/58153179/159821269-c5eac618-7bd7-4b9b-82c1-c77971a9e0e2.png)
![image](https://user-images.githubusercontent.com/58153179/159821289-43b8bd2d-1da4-4415-80c2-26e4bc23e924.png)

**I left the server on and went to sleep and got this Crash log**
![Screenshot_2022-03-24-07-05-53-989_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159893108-a3e96137-c33a-4586-ab2b-ed1b3fc0c76f.jpg)
![Screenshot_2022-03-24-07-06-07-279_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159893120-bb275127-b412-48c5-8a68-9a4c3622342b.jpg)
![Screenshot_2022-03-24-07-06-24-756_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159893128-4be31737-2b69-40f7-8167-af5efcc03304.jpg)
![Screenshot_2022-03-24-07-06-39-332_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159893130-bc16a127-d6cd-4574-931e-bdd9150501ab.jpg)
![Screenshot_2022-03-24-07-06-50-971_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159893134-89671a4a-191a-419f-bd0e-e90ce92c186a.jpg)
![Screenshot_2022-03-24-07-07-00-873_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159893143-41022596-1edb-498c-b2a8-b2b18f483110.jpg)

note: crashes have been slower to happen.

**Comment by ZhengPeiRu21** [comment]
Thank you for the helpful reporting. This should be resolved in https://github.com/ZhengPeiRu21/mod-playerbots/commit/31509aac683ca9ed3c1198eb09830e6db9543a81.
