### ISSUE TITLE
CI builds fail

### ISSUE THREAD

**Issue by qudzy** [ZhengPeiRu21/mod-playerbots#44]
Below is a snippet of where the [latest workflow](https://github.com/ZhengPeiRu21/mod-playerbots/runs/5993472093) (at the time of writing) fails.
```
[ 73%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/world_script_loader.cpp.o
[ 74%] Linking CXX static library libscripts.a
[ 74%] Built target scripts
make: *** [Makefile:146: all] Error 2
```
Upon closer inspection, it seems like every workflow has failed on the build step.

I encountered this exact issue while attempting to setup a compilation environment using Docker. I ended up switching to developing on Windows where this error does not occur.

**Comment by ZhengPeiRu21** [comment]
Thank you for the report, and sorry for the delayed response. The CI build has never worked properly and has been removed so that it no longer reports failed workflows.
