### ISSUE TITLE
2022/4/22

### ISSUE THREAD

**Issue by biancong1208** [ZhengPeiRu21/mod-playerbots#46]
Compilation succeeded but unable to start server.
![image](https://user-images.githubusercontent.com/93648230/164739703-70e0e7f7-8802-459e-a133-346b282e4caf.png)

**Comment by ZhengPeiRu21** [comment]
Thank you for the report. This issue is not from the Playerbots module; it is an AzerothCore issue. The max SQL packet size for your database is too small. This can be fixed by running this SQL command: SET GLOBAL max_allowed_packet=1073741824;

**Comment by biancong1208** [comment]
> Thank you for the report. This issue is not from the Playerbots module; it is an AzerothCore issue. The max SQL packet size for your database is too small. This can be fixed by running this SQL command: SET GLOBAL max_allowed_packet=1073741824;

The problem is solved, thank you very much.
