### ISSUE TITLE
Compilation error in docker setup

### ISSUE THREAD

**Issue by gregflynn** [ZhengPeiRu21/mod-playerbots#48]
Gave this mod a whirl today, got 2 build errors on Linux:

![image](https://user-images.githubusercontent.com/295898/165524632-a3615f89-7c85-4f8e-8e65-db0be68aafa8.png)

![image](https://user-images.githubusercontent.com/295898/165524713-2954f46f-9f3e-4042-ba3c-b1c81b823e2c.png)

Let me know if there's more information I can provide or further steps to assist debugging.

**Comment by ZhengPeiRu21** [comment]
Thank you for the report, these may be due to recent AC upstream changes. I will look into it!

**Comment by ZhengPeiRu21** [comment]
Are you still seeing issues with the latest version of my AC branch?

**Comment by gregflynn** [comment]
> Are you still seeing issues with the latest version of my AC branch?

Apologies for my delay, I'm using mainline AC at [this commit](https://github.com/azerothcore/azerothcore-wotlk/commit/77720506c02bb8be1fc2d8ddbad06dc181aeb940). I didn't realize this mod requires an AC branch at the moment if that's what you mean in your previous comment, apologies again if that's the case.

**Comment by gregflynn** [comment]
Closing, I see you updated the README, apologies for the noise!
