### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by YuLongGongWu** [ZhengPeiRu21/mod-playerbots#49]
我觉得少了类PlayerbotsDatabase 能麻烦上传一下么？
I think without the class playerbotsdatabase, can you please upload it?

/home/bladnir/azerothcore/modules/mod-playerbots-AzerothCore/src/GuildTaskMgr.cpp:504:5: fatal error: unknown type name 'PlayerbotsDatabasePreparedStatement'; did you mean 'CharacterDatabasePreparedStatement'?
    PlayerbotsDatabasePreparedStatement* stmt = PlayerbotsDatabase.GetPreparedStatement(PLAYERBOTS_SEL_GUILD_TASKS_BY_VALUE);

**Comment by ZhengPeiRu21** [comment]
不好意思让你等久了！刚看到这个issue了。你在用正确的AzerothCore fork和branch吗？应该用这个:
https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbot

**Comment by YuLongGongWu** [comment]
首先谢谢你 应该是我分支用错了 我使用的是 https://github.com/azerothcore/azerothcore-wotlk 的master分支。
不过我看了一下你代码，就是把整个的mod-playerbots功能作为一个module，我的个人感觉也许其实playerbotsdatabase 这个类放在mod-playerbots也是个不错的选择，因为这个类看上去就是连接一下数据库，不过我的C++水平还不够，我只是说一个想法而已，仅供参考。

First of all, thank you. I should have used the wrong branch. I used https://github.com/azerothcore/azerothcore-wotlk The master branch of.
However, I looked at your code and took the whole mod playerbots function as a module. My personal feeling is that maybe in fact, the class playerbots database is also a good choice in mod playerbots, because this class seems to connect to the database, but my C + + level is not enough. I just said an idea for reference only.

**Comment by YuLongGongWu** [comment]
首先谢谢你 应该是我分支用错了 我使用的是 https://github.com/azerothcore/azerothcore-wotlk 的master分支。
不过我看了一下你代码，就是把整个的mod-playerbots功能作为一个module，我的个人感觉也许其实playerbotsdatabase 这个类放在mod-playerbots也是个不错的选择，因为这个类看上去就是连接一下数据库，不过我的C++水平还不够，我只是说一个想法而已，仅供参考。

First of all, thank you. I should have used the wrong branch. I used https://github.com/azerothcore/azerothcore-wotlk The master branch of.
However, I looked at your code and took the whole mod playerbots function as a module. My personal feeling is that maybe in fact, the class playerbots database is also a good choice in mod playerbots, because this class seems to connect to the database, but my C + + level is not enough. I just said an idea for reference only.

**Comment by YuLongGongWu** [comment]
谢谢您 已经成功编译过去了
