### ISSUE TITLE
Another variant of simple NPC-bot

### ISSUE THREAD

**Issue by Bogir** [ZhengPeiRu21/mod-playerbots#50]
It can be ported easier
https://github.com/mthsena/trinitycore_scripts/tree/master/scripts/C%2B%2B/NPC_Bots

**Comment by ZhengPeiRu21** [comment]
Thank you for sharing this! It is truly much simpler and easier to port, but also missing many features. I think having both available is a good option, but I am already have trouble find time to maintain just one bot project, so it will need to be work for another! Haha. ^_^

**Comment by Bogir** [comment]
>  so it will need to be work for another! Haha. ^_^

You're right, this version is much simplier. I'm using something like this for 2 years and found that such functionality is quite sufficient.

Compilation of 16 files is faster than 800+ files of PlayerBot and almost no errors and issues on it)

**Comment by OpexNSK** [comment]
Indeed, I also used these bots. There is enough functionality only for PvE, but they work without errors and stably. Management is also more convenient

**Comment by samuel-edmund-morgan** [comment]
> Indeed, I also used these bots. There is enough functionality only for PvE, but they work without errors and stably. Management is also more convenient

Did you use it with TrinityCore or AC ?

**Comment by OpexNSK** [comment]
TrinityCore

**Comment by ZhengPeiRu21** [comment]
I am going to close this issue because there is nothing to resolve. Please let me know if you have any concerns.
