### ISSUE TITLE
Add this to the AC catalogue please 🙏 

### ISSUE THREAD

**Issue by Helias** [ZhengPeiRu21/mod-playerbots#52]
Hey, you can easily add this repository to the AzerothCore catalogue, adding the github topic "azerothcore-module".

**Comment by Bogir** [comment]
> Hey, you can easily add this repository to the AzerothCore catalogue, adding the github topic "azerothcore-module".

Compilation process goes 4 times longer (up to 35-45 minutes), and server is chashed too often.

**Comment by heyitsbench** [comment]
> Compilation process goes 4 times longer (up to 35-45 minutes), and server is chashed too often.

Hence why adding it to the catalogue and getting more eyes on it to try and fix its issues is a good idea.

**Comment by Helias** [comment]
I think adding it can only help

**Comment by ZhengPeiRu21** [comment]
Thank you for the encouraging! I've added the azerothcore-module topic to the repo. I will also update the README so it is clear that this currently still requires a custom branch.

**Comment by Bogir** [comment]
> Thank you for the encouraging!

Is it possible to mark this module as WIP in order to exclude unnecessary questions and any daring demands to fix unknown errors?
