### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by YuLongGongWu** [ZhengPeiRu21/mod-playerbots#58]
Player::_LoadInventory: player (GUID Full: 0x0000000000000001 Type: Player Low: 1, name: 'Rosa') has item (GUID Full: 0x4000000000018a1d Type: Item Low: 100893, entry: 38480) which can't be loaded into inventory (Bag GUID: 0, slot: 16) by reason 20. Item will be sent by mail.

SQL(p): INSERT INTO character_spell (guid, spell, specMask) VALUES (109, 697, 255)
 [ERROR]: [1062] Duplicate entry '109-697' for key 'character_spell.PRIMARY'
Clara: items could not be enchanted, wrong item type equipped
Clara: items could not be enchanted, wrong item type equipped
SQL(p): INSERT INTO character_spell (guid, spell, specMask) VALUES (109, 32244, 255)
 [ERROR]: [1062] Duplicate entry '109-32244' for key 'character_spell.PRIMARY'

worldserver启动后，没有任何人类账户登录，报大量上述错误。

**Comment by YuLongGongWu** [comment]
还有就是 是否有把日志打的更好一些的办法 现在报错 没有堆栈信息 也没有行号这些 有什么办法能改一下吗？

**Comment by lfox418** [comment]
SQL(p): INSERT INTO character_spell (guid, spell, specMask) VALUES (4033, 12677, 1)
 [ERROR]: [1062] Duplicate entry '4033-12677' for key 'PRIMARY'
 相同的错误，数据表里有对应的值了，不知道为什么总是会尝试写入。

**Comment by Dreathean** [comment]
@YuLongGongWu this should be resolved, please close out
