### ISSUE TITLE
fifth crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#6]
After more than 2 hours on, it crashed:
![Screenshot_2022-03-24-14-47-10-868_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159978793-c6cdbbd5-4974-47fe-bb01-4bbcf0cae5a0.jpg)
![Screenshot_2022-03-24-14-47-20-474_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159978803-4a4c8143-db7d-40c7-926d-860e75d340df.jpg)
![Screenshot_2022-03-24-14-47-28-564_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159978807-5fac505f-bfa7-4332-a2fb-f286e5fdd5c9.jpg)
![Screenshot_2022-03-24-14-47-40-618_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159978812-4a5cb796-2395-4337-99e6-30494f11f1fc.jpg)

**Comment by htc16** [comment]
**new fall**


![Screenshot_2022-03-24-15-04-16-031_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159981635-38bffc01-a20e-452a-80b2-b55b39dd3071.jpg)
![Screenshot_2022-03-24-15-04-37-779_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159981651-1e64dee3-ead6-4323-8eb3-7c8b6d379881.jpg)
![Screenshot_2022-03-24-15-04-48-957_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159981660-a5027e89-f03c-4859-b27f-c4b67233a880.jpg)
![Screenshot_2022-03-24-15-05-06-506_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159981663-5b53c1e2-e86f-4250-84f3-a822c852a321.jpg)
![Screenshot_2022-03-24-15-05-11-740_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/159981664-21f7a1f3-4c52-44c1-8128-92092efc10c3.jpg)

**Comment by ZhengPeiRu21** [comment]
Please try again after latest commit https://github.com/ZhengPeiRu21/mod-playerbots/commit/0033ae996875d5fbc2e7391450152d4634d62175 and let me know if you continue to see this crash. Thank you!
