### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by YuLongGongWu** [ZhengPeiRu21/mod-playerbots#66]
/home/wow/azerothcore/modules/mod-playerbots/src/strategy/actions/MovementActions.cpp
这个类 1051行 调用的方法的名字换了，换成GetThreatMgr 就过去了
HostileReference* ref = target->GetThreatMgr().getCurrentVictim();

**Comment by ZhengPeiRu21** [comment]
This should now be resolve after the latest fixes. Please re-open this issue and let me know if there continues to be issue. Thanks!

现在应该都修好了！可以再试试。

**Comment by YuLongGongWu** [comment]
好的谢谢，我已经试过了，没有问题
