### ISSUE TITLE
sixth fall

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#7]
![Screenshot_2022-03-24-17-19-06-145_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160003060-e5615ec1-58a9-435c-ad94-5a2b95838861.jpg)
![Screenshot_2022-03-24-17-19-15-894_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160003068-6549fe26-b2aa-4f90-ba9e-d5d67d842325.jpg)

**Comment by htc16** [comment]
![image](https://user-images.githubusercontent.com/58153179/160029774-4423edd5-30c7-4629-9c19-5b1a87147c4d.png)
![image](https://user-images.githubusercontent.com/58153179/160029829-62b1fed2-b659-4577-b48a-c569ef4573df.png)
![image](https://user-images.githubusercontent.com/58153179/160029869-bee21114-9169-478a-883f-8c5bc49c1341.png)
![image](https://user-images.githubusercontent.com/58153179/160029891-b0f9d011-9913-424d-97db-26f397bffd8f.png)

**Comment by htc16** [comment]
![image](https://user-images.githubusercontent.com/58153179/160030426-220cd625-6d99-452e-8fe6-b40ece6a77bb.png)
![image](https://user-images.githubusercontent.com/58153179/160030467-4a7a87a1-c619-4ea5-978b-db96ea103dd0.png)
![image](https://user-images.githubusercontent.com/58153179/160030497-c0b3dd5e-eff2-4daa-9327-f9427c70ecb4.png)
![image](https://user-images.githubusercontent.com/58153179/160030527-1d954923-75bb-4565-87c2-8c9d1e6c8ee8.png)
![image](https://user-images.githubusercontent.com/58153179/160030569-c0d6a2cd-eaa6-4a85-a297-2c31790e9c71.png)

**Comment by htc16** [comment]
![image](https://user-images.githubusercontent.com/58153179/160111033-bcc61fdd-84fe-4376-a237-a6a765c530f0.png)
![image](https://user-images.githubusercontent.com/58153179/160111100-a36ac872-03af-4d79-afaa-27cb5458572e.png)
![image](https://user-images.githubusercontent.com/58153179/160111175-2017761f-751e-4937-ab8a-139e37ad8026.png)
![image](https://user-images.githubusercontent.com/58153179/160111311-0d8116a8-49f0-4f13-9121-8ed5ad4a594f.png)
![image](https://user-images.githubusercontent.com/58153179/160111486-ae970560-e372-488d-a741-0a6db1281fd1.png)
![image](https://user-images.githubusercontent.com/58153179/160111534-7ca13515-3564-472b-af4d-945efe9af550.png)
![image](https://user-images.githubusercontent.com/58153179/160111705-2603b440-e243-4c16-9501-3ec1ac7e78b7.png)

**Comment by htc16** [comment]
![image](https://user-images.githubusercontent.com/58153179/160135783-04e4d91a-6dcb-4acb-8cc6-6b3b49b9a0a5.png)
![image](https://user-images.githubusercontent.com/58153179/160135843-28773177-aeda-4ed9-b466-64ed1fd4c511.png)
![image](https://user-images.githubusercontent.com/58153179/160135894-e426b0f7-a01f-470b-a03c-9d9c9e75716c.png)

**Comment by ZhengPeiRu21** [comment]
Commit https://github.com/ZhengPeiRu21/mod-playerbots/commit/bb737ed928a4d0c79ccd3d7bea9b10a2bb03c547 should help fix some of this issue. Could you please try again with this latest update?

**Comment by Bogir** [comment]
![изображение](https://user-images.githubusercontent.com/25766571/160174085-77cb653d-7d97-4db9-9e5c-b29d6f9f4614.png)

What can it be? I've cloned https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbot branch,
and added `mod_playerbot` folder into it. I've miss something?
cMake 3.23
VC 17.1.2 2022
Win7x64

**Comment by ZhengPeiRu21** [comment]
> What can it be? I've cloned https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbot branch, and added `mod_playerbot` folder into it. I've miss something? cMake 3.23 VC 17.1.2 2022 Win7x64

Is your Playerbot module on the AzerothCore branch? The master branch is cMangos bots code.

**Comment by Bogir** [comment]
> Is your Playerbot module on the AzerothCore branch? The master branch is cMangos bots code.

https://github.com/ZhengPeiRu21/mod-playerbots

Does it must have `mod_playerbots` folder name, or `mod-playerbots-AzerothCore` ?
Or `mod-playerbots`? :)

**Comment by ZhengPeiRu21** [comment]
> > Is your Playerbot module on the AzerothCore branch? The master branch is cMangos bots code.
> 
> https://github.com/ZhengPeiRu21/mod-playerbots
> 
> Does it must have `mod_playerbots` folder name, or `mod-playerbots-AzerothCore` ? Or `mod-playerbots`? :)

It should be mod_playerbots. Please ensure mod_playerbots is on the branch named "AzerothCore", not "master". (The branch for the module self, not the branch of the AzerothCore core code. Sorry, it is very confusing! Haha.)

**Comment by Bogir** [comment]
![изображение](https://user-images.githubusercontent.com/25766571/160179535-e5bc2af8-9635-4001-bde1-1cb2cbcb82f3.png)
![изображение](https://user-images.githubusercontent.com/25766571/160179562-5b3bee41-90c9-4ee7-b2b6-1adcae5c9f10.png)
Branch named `Playerbot`, not `AzerothCore`. Is it incorrect?

I've cloned it from here:
![изображение](https://user-images.githubusercontent.com/25766571/160180227-fe89d460-c083-47df-80aa-ebeb6e360d31.png)

**Comment by ZhengPeiRu21** [comment]
That is correct for the core, but the module also needs to be on correct branch:
![Capture](https://user-images.githubusercontent.com/98835050/160181112-e0890f67-3805-49c8-87df-5a55e83e5052.PNG)

EDIT: Sorry, it does seem the only public branch is the AzerothCore branch, so this should not be the problem.

**Comment by ZhengPeiRu21** [comment]
Did you re-run Cmake after place the module folder?

**Comment by Bogir** [comment]
> Did you re-run Cmake after place the module folder?

I not changed it. folder name was `mod_playerbots` as it setted in loader
![изображение](https://user-images.githubusercontent.com/25766571/160182588-34a45e14-b477-493b-9f94-e80bed2e3c9f.png)

I completelly don't understand what's going on :)

**Comment by Bogir** [comment]
maybe the module is not initialized? 

all errors appears on `#ifdef` as mod is not defined

![изображение](https://user-images.githubusercontent.com/25766571/160185144-02d6118c-d966-4153-868d-f1590816c7de.png)

**Comment by ZhengPeiRu21** [comment]
Sorry, I also am not sure. It is very strange. Maybe try to check out everything and build again in a fresh directory?

**Comment by Bogir** [comment]
> Sorry, I also am not sure. It is very strange. Maybe try to check out everything and build again in a fresh directory?

I cloned again, changed dir and drive)   And post my trouble here after it.
Very strange

**Comment by Bogir** [comment]
Once again:

Is it correct branch?
https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbot

Correct Module?
https://github.com/ZhengPeiRu21/mod-playerbots

And is this  a correct string? (NO!)
https://github.com/ZhengPeiRu21/azerothcore-wotlk/blob/7d7e66cbe48f3de151c270fb523d5ddfe7a7f2df/modules/CMakeLists.txt#L87

![изображение](https://user-images.githubusercontent.com/25766571/160234810-13046822-7134-404f-850a-6ceebd533298.png)
