### ISSUE TITLE
custom_unlocked_appearnces 

### ISSUE THREAD

**Issue by rogerc66** [ZhengPeiRu21/mod-playerbots#73]
<img width="818" alt="666" src="https://user-images.githubusercontent.com/4217584/170845450-e10bd525-8899-4a44-b2b2-092f68f7779c.PNG">
looks like there is a table missing, and there is no respect sql in update folder

**Comment by ZhengPeiRu21** [comment]
That table is added by the transmog module. Did you compile with that module as well?

**Comment by rogerc66** [comment]
> That table is added by the transmog module. Did you compile with that module as well?

Yes, Thank you for enlighten me, I forgot modules sql, I applied sql provided by the module and now it runs fine, please close this issure.
