### ISSUE TITLE
Idea: bots can join battlefields and arenas

### ISSUE THREAD

**Issue by yuanf225** [ZhengPeiRu21/mod-playerbots#82]
Would be great if bots could fill up into the battlefield or arena

**Comment by heyitsbench** [comment]
I think that's already the intent, (There's even a video of the Ike3 bots in either BG/arena don't remember which functioning quite well) but as of right now, they just have stability issues that need ironing out to get them in the instances.

**Comment by ZhengPeiRu21** [comment]
Thank you for share the idea! Yes, this is already supported and should work once the other issues with the bots are all resolved.
