### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#84]
This error only happens when I activate the playerbots mod.

![image](https://user-images.githubusercontent.com/58153179/172953961-0b8b2dbd-128f-4618-afa4-09c110004d47.png)

If needed, I can provide more information about the OS and other settings.

**Comment by heyitsbench** [comment]
When does it happen, just immediately after the worldserver is started?

**Comment by htc16** [comment]
> When does it happen, just immediately after the worldserver is started?

is the moment that loads the bots module at startup.

**Comment by MoonyHsiao** [comment]
@benjymansy123  i have same problem but happen randomly mayby after the worldserver is started 5~60min
