### ISSUE TITLE
Some problems in the process of playing the game

### ISSUE THREAD

**Issue by biancong1208** [ZhengPeiRu21/mod-playerbots#9]
1. The playerbot does not seem to know to turn around, even if it is being attacked.
![2022-03-24_194541](https://user-images.githubusercontent.com/93648230/160121435-0a507ef3-ab24-446d-92dd-20ad13e6a516.png)
2. The playerbot seems to rarely attack actively, mostly standing and making different expressions.
![2022-03-24_200726](https://user-images.githubusercontent.com/93648230/160121475-2fff630f-3a2c-4cd6-82be-d5d2958ee706.png)
3. An error is displayed when talking to the playerbot.
![2022-03-24_200814](https://user-images.githubusercontent.com/93648230/160121523-5a665499-5611-4a7d-967f-3cef77f2dcf5.png)

**Comment by ZhengPeiRu21** [comment]
Thank you for the helpful report and screenshots. I am investigate how strategy strings are getting loaded as formations, which should help with resolve this.

As a temporary help, the bots may be more responsive if you decrease AiPlayerbot.ReactDelay in the config.

**Comment by biancong1208** [comment]
> Thank you for the helpful report and screenshots. I am investigate how strategy strings are getting loaded as formations, which should help with resolve this.
> 
> As a temporary help, the bots may be more responsive if you decrease AiPlayerbot.ReactDelay in the config.

Thanks a lot for your reply, I will try to decrease AiPlayerbot.ReactDelay in the config.
By the way, can you read Chinese? Because my screenshot environment is all in Chinese, if you don't understand, I can try to change it to English.
I got a lot of errors when compiling just now, the prompts are "undeclared identifier" and "modules.lib does not exist", is there something wrong with my operation during the compilation process?
![2022-03-26_203804](https://user-images.githubusercontent.com/93648230/160244674-308eaa07-5e6a-4bd4-a9ad-3a6b1b11b053.png)

**Comment by htc16** [comment]
> Thanks a lot for your reply, I will try to decrease AiPlayerbot.ReactDelay in the config.
> By the way, can you read Chinese? Because my screenshot environment is all in Chinese, if you don't understand, I can try to change it to English.
> I got a lot of errors when compiling just now, the prompts are "undeclared identifier" and "modules.lib does not exist", is there something wrong with my operation during the compilation process?

On linux there are also a lot of warning messages, I think it's because the base is under development and there's a lot to fix and stabilize before the warnings are removed. Zheng has been doing everything himself, which can delay the entire fix. But in my opinion this is the best mod developed so far. And Zheng does a great job.

**Comment by biancong1208** [comment]
> On linux there are also a lot of warning messages, I think it's because the base is under development and there's a lot to fix and stabilize before the warnings are removed. Zheng has been doing everything himself, which can delay the entire fix. But in my opinion this is the best mod developed so far. And Zheng does a great job.

Yes, of course, I think so too, please don't get me wrong, I'm not posting these questions to urge or accuse people like @ZhengPeiRu21, @UltraNix and all the developers who make playerbot better, on the contrary, my thanks to you all With great respect. As a pharmaceutical R&D worker, I don't know C++, so I figured what I can do is to disclose the problem I have and wait patiently to fix it.
Thanks to all the partners who make playerbot better, thank you!

**Comment by htc16** [comment]
> > On linux there are also a lot of warning messages, I think it's because the base is under development and there's a lot to fix and stabilize before the warnings are removed. Zheng has been doing everything himself, which can delay the entire fix. But in my opinion this is the best mod developed so far. And Zheng does a great job.
> 
> Yes, of course, I think so too, please don't get me wrong, I'm not posting these questions to urge or accuse people like @ZhengPeiRu21, @UltraNix and all the developers who make playerbot better, on the contrary, my thanks to you all With great respect. As a pharmaceutical R&D worker, I don't know C++, so I figured what I can do is to disclose the problem I have and wait patiently to fix it. Thanks to all the partners who make playerbot better, thank you!

Yes, and we have to share all the bugs found, so that the mod becomes even better.

**Comment by ZhengPeiRu21** [comment]
> Thanks a lot for your reply, I will try to decrease AiPlayerbot.ReactDelay in the config. By the way, can you read Chinese? Because my screenshot environment is all in Chinese, if you don't understand, I can try to change it to English. 

Yes, I myself am a Chinese, so Chinese screenshots is fine. ^_^ Thank you for post the compilation warnings. I will test more compiling on Linux to resolve some of these. Are you still can compile successfully despite the warnings?

**Comment by biancong1208** [comment]
> Yes, I myself am a Chinese, so Chinese screenshots is fine. ^_^ Thank you for post the compilation warnings. I will test more compiling on Linux to resolve some of these. Are you still can compile successfully despite the warnings?

Hi, thanks for the reply.
Unfortunately, the compilation failed.
![2022-03-27_123601](https://user-images.githubusercontent.com/93648230/160266971-6aad5271-f318-4e71-a07a-5837229d2b66.png)
I compiled it under windows11, and the compilation environment is as follows:
![2022-03-27_123917](https://user-images.githubusercontent.com/93648230/160266986-82df17ff-ae93-4d75-8d6d-d101e445ee5c.png)

**Comment by ZhengPeiRu21** [comment]
@biancong1208 Are you still seeing trouble of the compiling? Linking error like you are seeing usually means dirty build directory. Do you still see this error with a clean build?

**Comment by biancong1208** [comment]
> @biancong1208 Are you still seeing trouble of the compiling? Linking error like you are seeing usually means dirty build directory. Do you still see this error with a clean build?

HI, @ZhengPeiRu21  I found out that it was my problem. I named the "mod-playerbots" in the "modules" folder, so there were so many errors. Renaming it to "mod-playerbots-AzerothCore" didn't cause such errors.
