### ISSUE TITLE
ASSERTION FAILED

### ISSUE THREAD

**Issue by biancong1208** [ZhengPeiRu21/mod-playerbots#96]
#----------------------------------------------------------------------#
>> ASSERTION FAILED
# Location 'D:\AzerothCore\Core\src\server\game\Chat\Chat.cpp:253'
# Function 'ChatHandler::BuildChatPacket'
# Condition 'channelName.length() > 0'
#----------------------------------------------------------------------#
[已退出进程，代码为 3221226528 (0xc0000420)]
![image](https://user-images.githubusercontent.com/93648230/181800392-4c751859-5a67-4c30-be12-36df8798c72d.png)

**Comment by Hughcoyan** [comment]
服务器里的DBC好像不支持中文的  用了中文机器人不会使用技能 还有这个频道DBC中文后出现宕机

**Comment by ZhengPeiRu21** [comment]
Has anyone experience this with a enUS client?

**Comment by marquesini1992** [comment]
> Has anyone experience this with a enUS client?

 I use esES client and have this problem, I will try with a enUS client and answer later
------- update: 9/9/22
With extraction  dbc/maps from enUS client no present this problem, server work fine.

**Comment by ZhengPeiRu21** [comment]
Resolved in https://github.com/ZhengPeiRu21/mod-playerbots/commit/f88f49471a1f3f0664d8f5323983a97cd9297e98.
